# Generated by Django 4.2.6 on 2023-10-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0002_financialrecord_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='credit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='debit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
    ]
