# Generated by Django 4.2.6 on 2023-10-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0003_alter_financialrecord_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='currency',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=16),
        ),
    ]
