# Generated by Django 4.2.6 on 2023-11-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
