# Generated by Django 4.2.6 on 2023-11-11 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0003_remove_line_user_binding_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line_user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='line_user',
            name='line_user_id',
        ),
    ]
