# Generated by Django 4.2.6 on 2023-11-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0004_remove_line_user_email_remove_line_user_line_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_user',
            name='line_user_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
