# Generated by Django 4.2.6 on 2023-11-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0005_line_user_line_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line_user',
            old_name='line_user_id',
            new_name='request_id',
        ),
    ]
